version: 2

updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "./brainfree_ui/" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    directory: "./brainfree_ui/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"

    schedule:
      interval: "weekly"
